server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
elastic.apm.active: true
elastic.apm.serverUrl: "http://apm:8200"
# elastic.apm.secretToken: "secret"